apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: benthos-playground
build:
  artifacts:
    - image: benthos-dashboard
      context: benthos-dashboard
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*.yaml
