apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: benthos-playground
  labels:
    app: kafka
spec:
  clusterIP: None # Headless service for stable network identities
  ports:
  - port: 9092
    name: plaintext
  - port: 9093
    name: controller
  selector:
    app: kafka