input:
  kafka:
    addresses:
      - kafka:9092
    topics:
      - audit_trail
    consumer_group: audit_trail

pipeline:
  threads: 4
  processors:
    - mapping: |
        #!blobl
        root = if this.resource_sub_type != "LOGIN" &&
                  this.resource_sub_type != "CREATE" &&
                  this.resource_sub_type != "ACCOUNT_RECOVERY" &&
                  this.resource_sub_type != "PASSWORD_CHANGE" {
                    deleted()
                  }

    - mapping: |
        #!blobl
        root = this
        root.someField = "MAPPED"

output:
  kafka:
    addresses:
      - kafka:9092
    topic: fds_audit_trail