input:
  kafka:
    addresses:
      - kafka:9092
    topics:
      - users
    consumer_group: benthos_consumer

pipeline:
  processors:
    - mapping: |
        root = this
        root.id = uuid_v4()

output:
  kafka:
    addresses:
      - kafka:9092
    topic: enriched_users